services:
  web-patron:
    container_name: web-patron
    build: ./
    environment:
      CONFIG_FILE: /config/config.yml
      NODE_ENV: production
      NEXT_PUBLIC_MAGAZINES_ENV: playground
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
